Add presentation materials for March 2017
NashvilleCocoaHeads/Presentation-Archive pull request #9
Opened 2018-01-18 18:09 UTC by addisonwebb

Adds presentation materials for March 2017.

Checklist:

- [x] Updated this month's README.md file (e.g. `/01-January/README.md`)
- [x] Added source code (if any).
- [x] Added presentation materials (if any).
- [x] Added relevant notes (if any).

Please contact @blakemerryman or @addisonwebb if you have any issues.

2018-01-18 20:24 UTC, blakemerryman approved these changes

2018-01-18 20:24 UTC, blakemerryman commented on .gitmodules
> +[submodule "2017/03-March/parse-server-setup-guide"]
Oooh! Fancy submodules!

2018-01-18 20:26 UTC, blakemerryman reviewed
Do we want to enforce code check-in? Or is submodules ok?

2018-01-18 23:56 UTC, addisonwebb commented
Good question. I only used a submodule here since I did end up creating a public repo with the content of my presentation. I don't have a strong opinion either way. What do you think?

2018-01-19 00:19 UTC, blakemerryman commented
I think we should enforce check-in since it is an archive. If the developer wants to link back to their own repo, they can put that in the readme. 

Or we can just fork their projects... but that makes this whole repo irrelevant 😂

2018-01-19 02:56 UTC, addisonwebb commented
That makes sense to me. I'll check in the project.

2018-01-19 22:28 UTC, blakemerryman requested changes
Check-in version of code presented.

2018-02-01 04:08 UTC, blakemerryman commented
As discussed, we're forking code repos; just slides/notes/general-materials here.

2025-09-21 13:07 UTC, closed without merging